name: Build Lab07_Project
on:
    push:
        branches: [main]
        tags:
            - "v*.*.*"
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Agrupa execuções pela branch
  cancel-in-progress: true # Cancela execuções anteriores em andamento

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: Setup .Net Core SDK
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.x'

            - name: Restore Packages
              run: dotnet restore ./Lab07.IDNDev.Project.slnx

            - name: Build Solution
              run: dotnet build --no-restore ./Lab07.IDNDev.Project.slnx

            - name: Test
              run: dotnet test ./Lab07.IDNDev.Project.slnx --no-restore --no-build --logger trx --results-directory "TestResults"

            - name: Upload Articts
              uses: actions/upload-artifact@v6
              with:
                name: dotnet-test-results
                path: TestResults

            - name: Publish
              run: dotnet publish ./src/Services/IDNDev.Cadastro.Api/IDNDev.Cadastro.Api.csproj --no-restore -c Release -o ./publish
            
            - name: Upload Artifacts Publish
              uses: actions/upload-artifact@v6
              with:
                name: api
                path: ./publish

    build-docker-image:
        needs: [build]
        name: Build and Push Docker Image
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v6

          - name: Download Artifact Published
            uses: actions/download-artifact@v6
            with:
                name: api
                path: ./publish
                merge-multiple: false

          - name: Build Docker Image
            run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/idndev-cadastro-api .

          - name: Extract metadata (tags, labels)
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: |
                    ${{ secrets.DOCKERHUB_USERNAME }}/idndev-cadastro-api
                tags: |
                    type=sha
                    type=raw,value=latest
                    type=semver,pattern={{version}}

          - name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Push Docker Image # Envia a imagem para o Docker Hub.
            run: docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/idndev-cadastro-api