name: Build Lab07_Project
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }} # Agrupa execuções pela branch
  cancel-in-progress: true # Cancela execuções anteriores em andamento

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code
              uses: actions/checkout@v6

            - name: Setup .Net Core SDK
              uses: actions/setup-dotnet@v5
              with:
                dotnet-version: '10.x'

            - name: Restore Packages
              run: |
                dotnet restore ./Lab07.IDNDev.Project.slnx

            - name: Build Solution
              run: dotnet build --no-restore --configuration Release ./Lab07.IDNDev.Project.slnx

            - name: Test
              run: dotnet test ./src/Test/IDNDev.Cadastro.Test/IDNDev.Cadastro.Test.csproj --no-restore --no-build --logger trx --results-directory "TestResults"

            - name: Upload Articts
              uses: actions/upload-artifact@v6
              with:
                name: dotnet-test-results
                path: TestResults

            - name: Publish
              run: dotnet publish ./src/Services/IDNDev.Cadastro.Api/IDNDev.Cadastro.Api.csproj --no-restore --no-build --configuration Release --output ./publish
            
            - name: Upload Artifacts Publish
              uses: actions/upload-artifact@v6
              with:
                name: api
                path: ./publish

